### ISSUE TITLE
Fix M1 issues: Update Assumptions

### ISSUE THREAD

**Issue by zhengjiex** [zhengjiex/ICT2201_P5-8#46]
Assumptions for staff member and manager timeline is 1 week ahead of schedule.

Update the assumptions in the correct timeline:
Today is 4 Oct, Tuesday.
By 5 Oct, Wed, all staff should have indicated their availability for next week (10-16 oct).
After Wed 2359 hrs, staff cannot change availability for 10-16 oct.
If deadline is missed, they have until 6 oct, Thu, to send availability for 10-16 oct (must give reason for missing deadline).
Staff should be able to see job allocation on 7 oct, Fri morning.
7 oct, Fri noon is the deadline for rejecting a job.
The workload for next week (10-16 oct) will be released latest by 8 oct Sat.

Amend use case descriptions, non-functional requirements that reference this timeline

**Comment by Weijo** [comment]
Assumptions and requirements related to the timeline has been amended

**Comment by Weijo** [comment]
Assumptions and requirements related to the timeline has been amended
