### ISSUE TITLE
M2: Component Diagram

### ISSUE THREAD

**Issue by zhengjiex** [zhengjiex/ICT2201_P5-8#54]
Create components for:

- StaffWorkload
- UserManagement
- Staff UI
- ManagerWorkload
- JobPreference
- ManagerUI
- AdminManagement,
- Availability
- ITAdministratorUI
- ManagerRequest 
- StaffRequest
- Database

**Comment by ng-wl** [comment]
I have created components for the classes:

- IT_Administrator
- UserManagement
- AdminUI
- AvailabilityUI
- AvailabilityManagement
- Availability

**Comment by zhengjiex** [comment]
I have created components for the following:

- Staff
- Request, RequestManagement, StaffRequestUI, ManagerRequestUI

**Comment by Weijo** [comment]
I have created components:
- StaffWorkload
- UserManagement
- StaffUI

**Comment by amelia225** [comment]
I have created components for the following: 

- ManagerWorkload
- JobPreference
- ManagerUI
