### ISSUE TITLE
M2: Class Diagram

### ISSUE THREAD

**Issue by ng-wl** [zhengjiex/ICT2201_P5-8#69]
Create Entity Classes for:
- Manager
- Staff
- IT_Administrator
- User
- Request
- Availability
- Job_Preference
- Job

Create Control Classes for:
- UserManagement
- AdminManagement
- AvailabilityManagement
- JobPreferenceManagement
- RequestManagement
- WorkloadManagement

Create Boundary Classes for:
- ManagerWorkloadUI
- StaffWorkloadUI
- ManagerRequestUI
- StaffRequestUI
- JobPreferenceUI
- AvailabilityUI
- AdminManagementUI
- UserManagementUI

**Comment by Weijo** [comment]
I have created the following classes:
- StaffWorkloadUI,
- Workload,
- UserProfileUI, 
- ProfileManagement,
- User

**Comment by ng-wl** [comment]
I have created the following classes:

- IT_Administrator
- UserManagement
- AdminUI
- AvailabilityUI
- AvailabilityManagement
- Availability

**Comment by ng-wl** [comment]
I have created the following classes:

- IT_Administrator
- UserManagement
- AdminUI
- AvailabilityUI
- AvailabilityManagement
- Availability

**Comment by amelia225** [comment]
I have created the following classes:

WorkloadManagement
ManagerWorkloadUI, 
Manager
JobPreferenceUI 
JobPreferenceManagement 
JobPreference

**Comment by zhengjiex** [comment]
I have created the following classes:

- Request
- RequestManagement
- ManagerRequestUI
- StaffRequestUI
- Staff

**Comment by zhengjiex** [comment]
I have updatedthe following classes:

    Request
    RequestManagement
    ManagerRequestUI
    StaffRequestUI
    Staff

**Comment by ng-wl** [comment]
I have updated the following classes:

- IT_Administrator
- AdminManagement
- AdminManagementUI
- AvailabilityUI
- AvailabilityManagement
- Availability

**Comment by amelia225** [comment]
I have updated the following classes: 

- WorkloadManagement
- ManagerWorkloadUI
- Manager
- JobPreferenceUI
- JobPreferenceManagement
- JobPreference

**Comment by Weijo** [comment]
I have updated the following classes:
- StaffWorkloadUI
- Job
- UserManagementUI
- UserManagement
- User
