### ISSUE TITLE
M2: Apply Architectural Design

### ISSUE THREAD

**Issue by zhengjiex** [zhengjiex/ICT2201_P5-8#71]
The team has decided to use 3-tier Architectural Design

**Comment by Weijo** [comment]
I have applied 3-tier architectural design patterns for the components:
- StaffWorkloadUI
- StaffWorkload
- UserManagement
- UserManagementUI
- WorkloadDAO
- AccountDAO

**Comment by amelia225** [comment]
I have applied 3-tier architectural design patterns for the original components:

ManagerWorkload
JobPreference
ManagerUI

and expanded to the following components:

ManagerWorkloadUI
ManagerWorkload
JobPreference
JobPreferenceUI
JobPreferenceDAO
