### ISSUE TITLE
M2: Apply Design Patterns

### ISSUE THREAD

**Issue by zhengjiex** [zhengjiex/ICT2201_P5-8#72]
Design patterns:
- Factory method for User creation

Data Access Object Design Pattern:
- Availability
- JobPreference
- Workload
- Requests
- Accounts

**Comment by ng-wl** [comment]
I have applied the "Factory Method" design pattern for user creation, and applied the Data Access Object design pattern to create the Availability DAO class.

**Comment by zhengjiex** [comment]
I have applied the "Factory Method" design pattern for user creation, and applied the Data Access Object design pattern to create the RequestDAO class.

**Comment by zhengjiex** [comment]
I have applied the "Factory Method" design pattern for user creation, and applied the Data Access Object design pattern to create the RequestDAO class.

**Comment by Weijo** [comment]
I have applied the Data Access Object Design pattern to the User and Workload entities to create the AccountDAO and RequestDAO class
