### ISSUE TITLE
M3: Wireframe & Prototype

### ISSUE THREAD

**Issue by Weijo** [zhengjiex/ICT2201_P5-8#76]
Start date: 2 Nov 2022

Things to do:
- Design wireframe
- Write wireframe description
- Write README instructions for Figma
- Create wireframe demonstration video

**Comment by ng-wl** [comment]
I have completed writing the wireframe descriptions for IT Administrator

**Comment by Weijo** [comment]
I have completed writing the wireframe descriptions for Staff

**Comment by ng-wl** [comment]
I have written the README instructions for IT Administrator interface

**Comment by amelia225** [comment]
I have completed writing the wireframe descriptions for Manager

**Comment by amelia225** [comment]
I have written the README instructions for manager interface

**Comment by zhengjiex** [comment]
I have completed designing the wireframes

**Comment by zhengjiex** [comment]
I have completed the video M3.

**Comment by zhengjiex** [comment]
End date: 26 Nov 2022
