### ISSUE TITLE
M3: Black Box Testing - Write Test cases

### ISSUE THREAD

**Issue by Weijo** [zhengjiex/ICT2201_P5-8#78]
Start date 1 Nov 2022

For each use case, write test cases for each

**Comment by ng-wl** [comment]
Completed writing test cases for my assigned use cases (1,2,13,14)

**Comment by Weijo** [comment]
Completed writing test cases for my assigned use cases (1, 5, 9, 10)

**Comment by amelia225** [comment]
completed writing test cases for my assigned use cases (6, 7, 15, 16)

**Comment by zhengjiex** [comment]
Completed writing test cases for my assigned use cases (4,8,11,12)

**Comment by Weijo** [comment]
End date: 24/11/2022
